title: Portfolio de Soro Donassigué Mathieu
description: >-
  Data Engineer & AI Enthusiast basé à Abidjan. 
  Découvrez mes projets en ingénierie des données, machine learning et architecture cloud.
author: Soro Donassigué Mathieu

# Thème GitHub Pages (tu peux changer 'minimal' par 'cayman', 'hacker', 'slate', etc.)
theme: jekyll-theme-minimal

# Réseaux sociaux
github_username: soromathieu
linkedin_username: soromathieu

# Paramètres de construction (Build settings)
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Fichiers à exclure lors de la compilation du site
exclude:
  - README.md # Optionnel : à décommenter si tu as un index.md ou index.html séparé pour la page d'accueil
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
